import { parseSevData, parseVornData} from './data-utils'

export interface httpoptions {
  hostname: string
  path: string
  method: string
}

export interface vornResponse {
  weatherStations:  
    {
      airPressure: number,
      airPressureTendency: number,
      airPressureTrend: number,
      cloudbase1: number | null,
      coordinates: number[],
      dewPoint: number,
      humidity: number,
      id: string,
      precipitation: number,
      solarRadiation: number | null,
      temperature: number,
      title: string,
      visibility: number | null,
      weatherCode: string | null,
      webcam: string,
      windChill: number,
      windDirection: number,
      windSpeed: number, 
    }[] 
}

export interface sevResponse {
  tiden: string,
  SdDiesel_E: string,
  FoVand_E: string,
  MyVand_E: string,
  HeVand_E: string,
  VnVand_E: string,
  EiVand_E: string,
  StDiesel_E: string,
  StVand_E: string,
  HhVind_E: string,
  NeVind_E: string,
  VgDiesel_E: string,
  BoVand_E: string,
  SuSol_E: string,
  PoVind_E: string,
  RoVind_E: string,
  Minesto_E: string,
  Forka_E: string,
  VandH_E: string,
  OlieH_E: string,
  VindH_E: string,
  BiogasH_E: string,
  TidalH_E: string,
  VandS_E: string,
  OlieS_E: string,
  VindS_E: string,
  SolS_E: string,
  VandSev_E: string,
  OlieSev_E: string,
  VindSev_E: string,
  SolSev_E: string,
  BiogasSev_E: string,
  TidalSev_E: string,
  SumS_E: string,
  SumH_E: string,
  SumSev_E: string,
  SumGront_E: string,
  SdDiesel_P: string,
  FoVand_P: string,
  MyVand_P: string
  HeVand_P: string,
  EiVand_P: string,
  StDiesel_P: string,
  StVand_P: string,
  HhVind_P: string,
  NeVind_P: string,
  RoVind_P: string,
  VgDiesel_P: string,
  BoVand_P: string,
  SuSol_P: string,
  PoVind_P: string,
  Minesto_P: string,
  Forka_P: string,
  VandH_P: string,
  OlieH_P: string,
  VindH_P: string,
  BiogasH_P: string,
  TidalH_P: string,
  VandS_P: string,
  OlieS_P: string,
  VindS_P: string,
  SolS_P: string,
  VandSev_P: string,
  OlieSev_P: string,
  VindSev_P: string,
  SolSev_P: string,
  BiogasSev_P: string,
  TidalSev_P: string,
  SumS_P: string,
  SumH_P: string,
  Gront_P: string,
  Vatnid: string,
  Lomundaroyri: string,
  Heygadalur: string,
  Eidisvatn: string,
  Strandadalur: string,
  Ryskisvatn: string,
  Vatnsnesvatn: string,
}
const vornResponseExample = {
  'weatherStations': [
    {
      'airPressure': 991.20,
      'airPressureTendency': 6.00,
      'airPressureTrend': -2.60,
      'cloudbase1': 510.00,
      'coordinates': [
          350,
          317
      ],
      'dewPoint': 10.20,
      'humidity': 98.00,
      'id': 'AWS310',
      'precipitation': 0.40,
      'solarRadiation': 0.70,
      'temperature': 10.50,
      'title': 'Tórshavn',
      'visibility': 8474.00,
      'weatherCode': null,
      'webcam': '/Webcam/Havn.jpg',
      'windChill': 7.50,
      'windDirection': 127.00,
      'windSpeed': 6.90
    },
    {
      'airPressure': 990.30,
      'airPressureTendency': 6.00,
      'airPressureTrend': -1.90,
      'cloudbase1': null,
      'coordinates': [
          385,
          740
      ],
      'dewPoint': 10.70,
      'humidity': 100.00,
      'id': 'AWS311',
      'precipitation': 0.00,
      'solarRadiation': null,
      'temperature': 10.80,
      'title': 'Suðuroy',
      'visibility': null,
      'weatherCode': null,
      'webcam': '/Webcam/akr01.jpg;/Webcam/akr02.jpg',
      'windChill': 7.00,
      'windDirection': 104.00,
      'windSpeed': 11.10
    }
  ]}

const sevResponseExample = {
  "tiden":"2021-10-02 19:16",
  "SdDiesel_E":"6,46",
  "FoVand_E":"4,85",
  "MyVand_E":"1,79",
  "HeVand_E":"3,78",
  "VnVand_E":"10,41",
  "EiVand_E":"17,29",
  "StDiesel_E":"0,00",
  "StVand_E":"1,10",
  "HhVind_E":"5,01",
  "NeVind_E":"2,54",
  "VgDiesel_E":"2,43",
  "BoVand_E":"0,50",
  "SuSol_E":"0,00",
  "PoVind_E":"1,32",
  "RoVind_E":"1,65",
  "Minesto_E":"0,00",
  "Forka_E":"1,06",
  "VandH_E":"28,81",
  "OlieH_E":"6,46",
  "VindH_E":"9,20",
  "BiogasH_E":"1,06",
  "TidalH_E":"0,00",
  "VandS_E":"0,50",
  "OlieS_E":"2,43",
  "VindS_E":"1,32",
  "SolS_E":"0,00",
  "VandSev_E":"29,31",
  "OlieSev_E":"8,89",
  "VindSev_E":"10,52",
  "SolSev_E":"0,00",
  "BiogasSev_E":"1,06",
  "TidalSev_E":"0,00",
  "SumS_E":"4,25",
  "SumH_E":"45,53",
  "SumSev_E":"49,78",
  "SumGront_E":"40,89",
  "SdDiesel_P":"14,19",
  "FoVand_P":"10,65",
  "MyVand_P":"3,93",
  "HeVand_P":"8,30",
  "EiVand_P":"37,97",
  "StDiesel_P":"0,00",
  "StVand_P":"2,42",
  "HhVind_P":"11,00",
  "NeVind_P":"5,58",
  "RoVind_P":"3,62",
  "VgDiesel_P":"57,18",
  "BoVand_P":"11,76",
  "SuSol_P":"0,00",
  "PoVind_P":"31,06",
  "Minesto_P":"0,00",
  "Forka_P":"2,33",
  "VandH_P":"63,3",
  "OlieH_P":"14,2",
  "VindH_P":"20,2",
  "BiogasH_P":"2,3",
  "TidalH_P":"0,0",
  "VandS_P":"11,8",
  "OlieS_P":"57,1",
  "VindS_P":"31,1",
  "SolS_P":"0,0",
  "VandSev_P":"58,9",
  "OlieSev_P":"17,9",
  "VindSev_P":"21,1",
  "SolSev_P":"0,0",
  "BiogasSev_P":"2,1",
  "TidalSev_P":"0,0",
  "SumS_P":"8,54",
  "SumH_P":"91,46",
  "Gront_P":"82,10",
  "Vatnid":"-3,41",
  "Lomundaroyri":"-1,99",
  "Heygadalur":"-3,53",
  "Eidisvatn":"-4,25",
  "Strandadalur":"-1,56",
  "Ryskisvatn":"-0,77",
  "Vatnsnesvatn":"-0,77"
}

test('converts sev response to sdk params', () => {
  expect(parseSevData(sevResponseExample, 'exampleStream')).toStrictEqual(
    {
      DeliveryStreamName: 'exampleStream',
      Record: {
        Data: JSON.stringify( {
           "tiden":"2021-10-02 19:16",
           "SdDiesel_E":"6,46",
           "FoVand_E":"4,85",
           "MyVand_E":"1,79",
           "HeVand_E":"3,78",
           "VnVand_E":"10,41",
           "EiVand_E":"17,29",
           "StDiesel_E":"0,00",
           "StVand_E":"1,10",
           "HhVind_E":"5,01",
           "NeVind_E":"2,54",
           "VgDiesel_E":"2,43",
           "BoVand_E":"0,50",
           "SuSol_E":"0,00",
           "PoVind_E":"1,32",
           "RoVind_E":"1,65",
           "Minesto_E":"0,00",
           "Forka_E":"1,06",
           "VandH_E":"28,81",
           "OlieH_E":"6,46",
           "VindH_E":"9,20",
           "BiogasH_E":"1,06",
           "TidalH_E":"0,00",
           "VandS_E":"0,50",
           "OlieS_E":"2,43",
           "VindS_E":"1,32",
           "SolS_E":"0,00",
           "VandSev_E":"29,31",
           "OlieSev_E":"8,89",
           "VindSev_E":"10,52",
           "SolSev_E":"0,00",
           "BiogasSev_E":"1,06",
           "TidalSev_E":"0,00",
           "SumS_E":"4,25",
           "SumH_E":"45,53",
           "SumSev_E":"49,78",
           "SumGront_E":"40,89",
           "SdDiesel_P":"14,19",
           "FoVand_P":"10,65",
           "MyVand_P":"3,93",
           "HeVand_P":"8,30",
           "EiVand_P":"37,97",
           "StDiesel_P":"0,00",
           "StVand_P":"2,42",
           "HhVind_P":"11,00",
           "NeVind_P":"5,58",
           "RoVind_P":"3,62",
           "VgDiesel_P":"57,18",
           "BoVand_P":"11,76",
           "SuSol_P":"0,00",
           "PoVind_P":"31,06",
           "Minesto_P":"0,00",
           "Forka_P":"2,33",
           "VandH_P":"63,3",
           "OlieH_P":"14,2",
           "VindH_P":"20,2",
           "BiogasH_P":"2,3",
           "TidalH_P":"0,0",
           "VandS_P":"11,8",
           "OlieS_P":"57,1",
           "VindS_P":"31,1",
           "SolS_P":"0,0",
           "VandSev_P":"58,9",
           "OlieSev_P":"17,9",
           "VindSev_P":"21,1",
           "SolSev_P":"0,0",
           "BiogasSev_P":"2,1",
           "TidalSev_P":"0,0",
           "SumS_P":"8,54",
           "SumH_P":"91,46",
           "Gront_P":"82,10",
           "Vatnid":"-3,41",
           "Lomundaroyri":"-1,99",
           "Heygadalur":"-3,53",
           "Eidisvatn":"-4,25",
           "Strandadalur":"-1,56",
           "Ryskisvatn":"-0,77",
           "Vatnsnesvatn":"-0,77"
        }) + '\n'
      }
    }
  )
})

test('converts vorn response to sdk params', () => {
  expect(parseVornData(vornResponseExample, 'exampleStream')).toStrictEqual(
    {
      DeliveryStreamName: 'exampleStream',
      Records: [
        {
          Data: {
            'airPressure': 991.20,
            'airPressureTendency': 6.00,
            'airPressureTrend': -2.60,
            'cloudbase1': 510.00,
            'coordinates': [
                350,
                317
            ],
            'dewPoint': 10.20,
            'humidity': 98.00,
            'id': 'AWS310',
            'precipitation': 0.40,
            'solarRadiation': 0.70,
            'temperature': 10.50,
            'title': 'Tórshavn',
            'visibility': 8474.00,
            'weatherCode': null,
            'webcam': '/Webcam/Havn.jpg',
            'windChill': 7.50,
            'windDirection': 127.00,
            'windSpeed': 6.90
          }
        },
        {
           Data: {
             'airPressure': 990.30,
             'airPressureTendency': 6.00,
             'airPressureTrend': -1.90,
             'cloudbase1': null,
             'coordinates': [
                 385,
                 740
             ],
             'dewPoint': 10.70,
             'humidity': 100.00,
             'id': 'AWS311',
             'precipitation': 0.00,
             'solarRadiation': null,
             'temperature': 10.80,
             'title': 'Suðuroy',
             'visibility': null,
             'weatherCode': null,
             'webcam': '/Webcam/akr01.jpg;/Webcam/akr02.jpg',
             'windChill': 7.00,
             'windDirection': 104.00,
             'windSpeed': 11.10
          }
        }
      ]
    }
  )
})
